Есть несколько способов сделать массив NumPy
1) конвертация обычных списков 
2) Встроенные функции
3) Создание случайных данных 

In [1]:
import numpy as np

In [3]:
# 1-й ментод 
mylist = [1, 2, 3]
# преобразование оьычного массива в массив numpy 
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [4]:
type(myarr)

numpy.ndarray

In [6]:
# создадим матрицу 
my_matrix = [[1, 2, 3], [3, 3, 3], [2, 2, 2]]
np_my_matrix = np.array(my_matrix)
np_my_matrix

array([[1, 2, 3],
       [3, 3, 3],
       [2, 2, 2]])

In [7]:
# 2-й метод 
# метод размерности np.arange()
# например мы сгенерируем последовательность
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# еще мы можем указать шаг
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
# Иногда нам нужно создавать массивы бинарных чисел np.zeros()
# если мы напишем одно число, то создастся одномерный массив
np.zeros(5)
# Обратим внимание, что нули записаны с точкой, они с плавающей точкой 

array([0., 0., 0., 0., 0.])

In [11]:
# чтобы создать массив из нескольких чисел, мы передаем кортеж из двух чисел 
np.zeros((5,5))
# на выходе мы получаем мастрицу 5 на 5 состоющую из нулей 
# обратим внимание, что когда передаем кортеж, то первое число говорит о количестве строк, а второе это количество столбцов 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# создаем массив из единиц 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# еще один способ создать 
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
# создание единичной матрицы 
# передаем только один параметр 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# 3-й метод со случайными числами 
# создание одного числа 
np.random.rand(1)

array([0.37851178])

In [21]:
# массив случаных чисел 
np.random.rand(5, 2)

array([[0.63470342, 0.57543977],
       [0.17848014, 0.79500729],
       [0.00394669, 0.88629354],
       [0.93329582, 0.4906391 ],
       [0.08410297, 0.48084322]])

In [23]:
# Массив случайных числе с положительными и отрицательными значениями 
np.random.randn(5, 2)
# 

array([[-1.3649485 ,  0.02762257],
       [-2.45830594, -0.69136022],
       [ 0.85033178, -1.25594394],
       [-2.1282131 ,  0.25758049],
       [-0.16995472,  0.91002123]])

In [27]:
# эта ф-я возвращает целые случайные числа до 101 (не вклюбчая 101)
np.random.randint(0,101)

89

In [28]:
# последовательность чисел
np.random.randint(0,101, 5)

array([68, 25, 27, 23, 59])

In [29]:
# или кортеж 
# последовательность чисел
np.random.randint(0,101, (4, 5))

array([[34, 46, 92, 54, 40],
       [31, 84, 13, 92, 59],
       [33, 45,  5, 49, 11],
       [ 7,  2, 66, 35, 27]])

In [30]:
# Сейчас сделаем результаты воспроизводимыми 
# это начальное состояние генератора чисел 
# при этом все числа так же останутся рандомными, но мы можем зафиксировать начаольное программное число 
# обычно пишут 42
np.random.seed(42)
# далее выполянем В ЭТОЙ ЖЕ ячейке 
np.random.rand(4)
# мы получили те же числа, что и в видеолекции 


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
# сейчас попробуем переформатировать существующий одномерный массив в двумерный 
np_arr = np.arange(0, 25)
np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
# переформатрируем в двумерный массив 5 на 5  
np_arr = np_arr.reshape(5, 5)
# нужно обратить внимание, что мы должны сделать так, чтобы все элементы массива влезли 
# то есть ы не можем указать матрицу 5 на 4 
np_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
# далее рассмотрим получение максимальных и минимальных чисел 
# для этого создадим новый массив
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [34]:
# получение максимального значения 
ranarr.max()

99

In [ ]:
# получение минимального значения 
ranarr.min()

In [35]:
# получение ИНДЕКСА максимального числа 
ranarr.argmax()

5

In [36]:
# получение ИНДЕКСА минимального числа 
ranarr.argmin()

7

In [38]:
# получения типа массива 
# так как это не метод, а свойство, то пишем без ()
ranarr.dtype

dtype('int32')

In [39]:
# чтобы посмотреть форму и размер массива 
# так как это не метод, а свойство, то пишем без ()
ranarr.shape

(10,)

In [43]:
np_arr.shape

(5, 5)