Индексация и выборки 
1) Как получить один элемент 
2) Как получить срез нескольких элементов (slice)
3) Выбор элементов в режиме brodcast 
4) Индексация и выборки в случае двух измерений 
5) Условная выборка (conditional selection)

In [11]:
import numpy as np 

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# вывести один элемент 
arr[8]

8

In [14]:
# для вывода нескольких элементов 
arr[1:5]

array([1, 2, 3, 4])

In [15]:
# brodcast
# это подмена нескольких элементов массива другим одним значением 
# например у нас есть такой массив 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# мы можем срезу чисел или одному числу определенное значение 
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# вернем массив в исхожный вид 
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# слайсы 
slice_of_array = arr[0:5] # в данном случае мы создали не отдельные элементы, а ссылки на массив arr 
slice_of_array

array([0, 1, 2, 3, 4])

In [19]:
# теперь присвоим новые значение 
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [20]:
# поэтому у нас значения поменялись в основоном массиве 
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
#  если мы не хотим влиять на исходный массив то это нужно сделать явно то есть нам надо его скопировать 
arr_copy = arr.copy()
arr_copy


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
# то если мы сейчас выполним переприсвоение элементам массива новго значения у нас не затронется изначальный массив 
arr_copy[:] = 100
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
# далее перейдем к двумерным массивам 
# создадим новый двумерный список 
arr_2d = np.array([[5, 10, 25], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 25],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# предположим. что нам надо получить первую строку в матрице 
# мы можем указать первую строку в матрице 
arr_2d[0]

array([ 5, 10, 25])

In [30]:
# идли последнюю 
arr_2d[-1]

array([35, 40, 45])

In [31]:
# два способа получить элемент массива и они равносильны 
print(arr_2d[1,1], arr_2d[1][1])

25 25


In [32]:
# если мы хотим получить некоторые элементы массива 
# например получим первые две строки двумерного массива 
arr_2d[:2]

array([[ 5, 10, 25],
       [20, 25, 30]])

In [34]:
# но теперь мы хотим получить вторую и третью колонку 
arr_2d[:2, 1:]
# то есть мы через запятую передаем срез по колонкам 


array([[10, 25],
       [25, 30]])

In [35]:
# как для выбора конкретного элемента не работает такой метод для выбора некоторых колонок 
arr_2d[:2][1:] 

array([[20, 25, 30]])

In [36]:
# часто будем использовать выборку по условию (conditional selection)
# например снова создадим новый массив 
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# далее выведем условия, где элементы массива > 4 
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
# сохраним такой массив 
bool_arr = arr > 4

In [39]:
# и далее мы можем использовать этот массив для фильтрации элементов массива 
arr[bool_arr]
# то есть у нас вывелись те элементы массива, которые были True 

array([ 5,  6,  7,  8,  9, 10])

In [40]:
# обычно в два этапа не делают, а прописывают сразу 
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])