Индексация и выборки 
1) Как получить один элемент 
2) Как получить срез нескольких элементов (slice)
3) Выбор элементов в режиме brodcast 
4) Индексация и выборки в случае двух измерений 
5) Условная выборка (conditional selection)

In [1]:
import numpy as np 

In [4]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# вывести один элемент 
arr[8]

8

In [7]:
# для вывода нескольких элементов 
arr[1:5]

array([1, 2, 3, 4])

In [8]:
# brodcast
# это подмена нескольких элементов массива другим одним значением 
# например у нас есть такой массив 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# мы можем срезу чисел или одному числу определенное значение 
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
# вернем массив в исхожный вид 
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# слайсы 
slice_of_array = arr[0:5] # в данном случае мы создали не отдельные элементы, а ссылки на массив arr 
slice_of_array

array([0, 1, 2, 3, 4])

In [22]:
# теперь присвоим новые значение 
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [24]:
# поэтому у нас значения поменялись в основоном массиве 
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])