In [1]:
import numpy as np

In [2]:
# создаем массив от 0 до 9 
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# c numpy можно проводить элементарные операуции, например сложение и умножение 
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
# а так же можно сложить два массива, но нужно обратить внимание, что эти дава массива должны быть одинакового размера 
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# аналогично для умножения 
arr * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# и для деления 
(arr + 1) / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [9]:
# извлечение квадратного корня 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
# три гонометрические ф-ии 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
# логарифм
np.log(arr)
# обратим внимание, что в обыной математике на ноль делить нельзя 
# но в нампай это делать можно, но будет прописано предупредждение 

c:\Users\PETR\.conda\envs\My_ml_course\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [12]:
# сумма всех элементов массива 
arr.sum()

45

In [13]:
# среднее значение по массиву 
arr.mean()

4.5

In [14]:
# максимальное и минимальное значение 
print(arr.max(), arr.min())

9 0


In [15]:
# дисперсия
arr.var()

8.25

In [17]:
# среднее квадратичное отклонение 
arr.std()

2.8722813232690143

In [18]:
# создадим мастрицу 5 на 5 таким образом 
arr2D = np.arange(0, 25).reshape(5, 5)
arr2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# помимо того, что мы так же можем посмотреть сумму элементов такого массива 
arr2D.sum()

300

In [20]:
# мы можем посмотреть сумму по строкам и сумму по колонкам
# например axis = 0 - это колонки 
arr2D.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [21]:
# например axis = 1 - это строки  
arr2D.sum(axis = 1)

array([ 10,  35,  60,  85, 110])